🎉 Error on npm run relay
$ npm run relay
> relay-trim-right-error@1.0.0 relay /Users/peter-j.schmidt/Projects/relay-trim-right-error
> relay-compiler --src client/src --schema ./schema.graphql

Writing js
ERROR:
Error writing modules:
Error: Cannot find module 'trim-right'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.module.exports.Object.defineProperty.value (/Users/peter-j.schmidt/Projects/relay-trim-right-error/node_modules/relay-compiler/bin/relay-compiler:28688:18)
    at __webpack_require__ (/Users/peter-j.schmidt/Projects/relay-trim-right-error/node_modules/relay-compiler/bin/relay-compiler:30:30)
    at _trimRight (/Users/peter-j.schmidt/Projects/relay-trim-right-error/node_modules/relay-compiler/bin/relay-compiler:28434:39)
    at Buffer.get (/Users/peter-j.schmidt/Projects/relay-trim-right-error/node_modules/relay-compiler/bin/relay-compiler:28472:17)
    at Generator.generate (/Users/peter-j.schmidt/Projects/relay-trim-right-error/node_modules/relay-compiler/bin/relay-compiler:27980:22)
    at Generator.generate (/Users/peter-j.schmidt/Projects/relay-trim-right-error/node_modules/relay-compiler/bin/relay-compiler:27739:18)

Note: Needed a hack:
https://github.com/facebook/relay/issues/1880#issuecomment-307705428